services:
  quizz-app-front:
    container_name: quizz-app-frontcontainer
    build: .
    image: quizz-app-front:v1
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge